# Generated by Django 3.1.7 on 2021-03-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
