# Generated by Django 3.1.8 on 2021-04-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20210416_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.TextField(choices=[('Member', 'Member'), ('Moderator', 'Moderator')], default='Member'),
        ),
    ]
