# Generated by Django 3.1.8 on 2021-04-19 23:27

from django.db import migrations, models
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, validators=[forum.validators.ValidateAgainstBlacklist(['all', 'new', 'subscribed'])]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.TextField(choices=[(0, 'Member'), (1, 'Moderator'), (2, 'Requested')], default=0),
        ),
    ]
