# Generated by Django 3.1.8 on 2021-04-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210419_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Moderator'), (2, 'Requested')], default=0),
        ),
    ]
