# Generated by Django 3.1.8 on 2021-04-27 17:20

from django.db import migrations, models
import forum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20210420_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, validators=[forum.validators.ValidateAgainstBlacklist(['all', 'new', 'subscribed', 'update'])]),
        ),
    ]
