# Generated by Django 3.1.8 on 2021-04-30 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0012_auto_20210427_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('made_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.community')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='forum.comment')),
            ],
        ),
    ]
