name: Deploy to AWS
on:
  workflow_dispatch:
env:
  APP_NAME: mu
  APP_ENVIRONMENT: mu-dev-1
  AWS_REGION: us-east-1
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - run: |        
        python -m pip install --upgrade pip
        pip install awsebcli --upgrade
        
        eb init -i ${{ env.APP_NAME }} --platform python-3.4 --region ${{ env.AWS_REGION }} -k ${{ secrets.AWS_SSH_KEY }}
        eb deploy ${{ env.APP_ENVIRONMENT }}
